### ISSUE TITLE
Adding Permissions makes the plugin not work

### ISSUE THREAD

**Issue by shadowolfyt** [shadowolfyt/AvicusSMP#1]
http://imgur.com/xERcpeJ

**Comment by alexanderjoe** [comment]
Ok so, for your bug, it seems highest chances are its the wrong version.

**Comment by jasoryeh** [comment]
Please push the plugins folder for me and @alexanderjoe to figure out the issue. -Input

**Comment by alexanderjoe** [comment]
No access @jasoryeh

**Comment by jasoryeh** [comment]
Im telling him to push the folder.

**Comment by alexanderjoe** [comment]
Ok @jasoryeh 
Not sure if shadow is online though, might take a while

**Comment by jasoryeh** [comment]
Fixed
