### ISSUE TITLE
GUI Shop

### ISSUE THREAD

**Issue by jasoryeh** [shadowolfyt/AvicusSMP#11]
Easier to set up, less signs, less breaking, more time, faster.

**Comment by shadowolfyt** [comment]
Assumption of using this plugin: https://www.spigotmc.org/resources/guishop.2451/

**Comment by alexanderjoe** [comment]
I'll set it up soon if shadow hasnt

**Comment by alexanderjoe** [comment]
I'll work on this in a bit @shadowolfyt

**Comment by alexanderjoe** [comment]
Ok @shadowolfyt Koja wants to run a poll to see if players want gui v. signs.

**Comment by shadowolfyt** [comment]
Okay I'll create some poll or something in Discord

**Comment by shadowolfyt** [comment]
http://www.strawpoll.me/12385333

**Comment by alexanderjoe** [comment]
Vote was for GUI shop, starting implementation.

**Comment by jasoryeh** [comment]
Marking testing...

**Comment by shadowolfyt** [comment]
Started the work, you can probably expand more https://github.com/shadowolfyt/AvicusSMP/blob/plugins/GUIShop/Prices.txt

**Comment by shadowolfyt** [comment]
Seem to be getting this error alot... anything to be concerned about?
'WARN Plugin GUIShop v2.1 generated an exception while executing task 2121'

**Comment by shadowolfyt** [comment]
A request for GUI and commands shots and such for removal.
Close?

**Comment by jasoryeh** [comment]
Remove GUI shop. Player shop was enough.
