### ISSUE TITLE
Actionbar Announcements

### ISSUE THREAD

**Issue by jasoryeh** [shadowolfyt/AvicusSMP#14]
Can be seen in work here: <img src="https://proxy.spigotmc.org/af4c50a9a55aa729a0ffd53216ca0a07936a30f7?url=http%3A%2F%2Fwww.mvdw-software.be%2Fwp-content%2Fuploads%2F2014%2F10%2Factionbar2.gif" />

**Comment by alexanderjoe** [comment]
"but not too much so chat isn't flooded with announcements and vanilla feeling is preserved."

**Comment by alexanderjoe** [comment]
Added https://www.spigotmc.org/resources/actionbar.4754/
