### ISSUE TITLE
Sleep Function

### ISSUE THREAD

**Issue by shadowolfyt** [shadowolfyt/AvicusSMP#3]
Adding a sleep/ bed thing (no idea what it's called) that basically allows one person to sleep, and the night passes? People are able to cancel the sleep thing as well

Suggested by Crazy

**Comment by jasoryeh** [comment]
Can be done using command blocks. Search it up.

**Comment by shadowolfyt** [comment]
https://www.spigotmc.org/resources/single-player-sleep.20173/

I will add this afternoon

**Comment by alexanderjoe** [comment]
Quite sure essentials might already work with this

**Comment by alexanderjoe** [comment]
@shadowolfyt I am going to add the plugin.

**Comment by alexanderjoe** [comment]
Added and is working now.
