### ISSUE TITLE
Stolen items

### ISSUE THREAD

**Issue by shadowolfyt** [shadowolfyt/AvicusSMP#9]
People are reporting items being stolen. Is there something that can be added to prevent this from happening?

**Comment by shadowolfyt** [comment]
@alexanderjoe @jasoryeh

**Comment by shadowolfyt** [comment]
Possible Solution: https://dev.bukkit.org/projects/coreprotect

**Comment by alexanderjoe** [comment]
Sure I will add it and if the problem stops I will close it.

**Comment by jasoryeh** [comment]
How? Make sure they lockette their chests. Also I can't do much about it rn... no perms. Just here to open and close issues I guess.

**Comment by shadowolfyt** [comment]
It's that people are reporting spawners and hoppers being stolen, not so much chests because of Lockette.

**Comment by alexanderjoe** [comment]
Well corepeotect is installed so if anyone reports it's just use "/co i" and click where the spawned was.

**Comment by shadowolfyt** [comment]
Question: So like if the block was floating (like a spawner) do you put another block there, click on it and it will still give the information?

**Comment by alexanderjoe** [comment]
OK well, in theory this issue is fixed, make a new one if problem persists and staff can't find who stole a spawner.
